version: '3.4'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Copet@123
      POSTGRES_USER: copet-admin
      POSTGRES_DB: COPET_DB
    ports:
      - 15432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    networks:
      - postgres-network

  # PostgreAdmin UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: eduardo-paes@outlook.com
      PGADMIN_DEFAULT_PASSWORD: CopetSystem!2022
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - postgres-network

  # Web API
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 5555:443
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
