version: '3'
services:
  # PostgreSQL Database
  postgres-copetsystem:
    image: postgres:latest
    container_name: copet-system-db
    environment:
      POSTGRES_PASSWORD: Copet@123
      POSTGRES_USER: copet-admin
      POSTGRES_DB: COPET_DB
    ports:
      - 15432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    networks:
      - postgres-copetsystem-network

  # PostgreAdmin UI
  pgadmin-copetsystem:
    image: dpage/pgadmin4:latest
    container_name: copet-system-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: eduardo-paes@outlook.com
      PGADMIN_DEFAULT_PASSWORD: CopetSystem!2022
    ports:
      - 16543:80
    depends_on:
      - postgres-copetsystem
    networks:
      - postgres-copetsystem-network

  webapi-copetsystem:
    build: .
    command: >
      sh -c "dotnet ef database update &&
             dotnet WebAPI.dll"
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db

networks:
  postgres-copetsystem-network:
    driver: bridge
