name: Build and deploy .NET app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: GPIC-Staging-WebAPI
  AZURE_WEBAPP_PACKAGE_PATH: "/dist"
  DOTNET_VERSION: "7.0"
  SOLUTION_PATH: "src/CopetSystem.API.sln"

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build ${{env.SOLUTION_PATH}}

      - name: dotnet publish
        run: dotnet publish ${{env.SOLUTION_PATH}} -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}} --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: published_web_app
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Staging"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: published_web_app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
